"use strict";
// electron/llm/index.ts
// Central export for all LLM modules
Object.defineProperty(exports, "__esModule", { value: true });
exports.TINY_MODE_GENERAL_PROMPT = exports.TINY_FOLLOWUP_EMAIL_PROMPT = exports.TINY_SUMMARY_JSON_PROMPT = exports.TINY_TITLE_PROMPT = exports.TINY_CODE_HINT_PROMPT = exports.TINY_CLARIFY_PROMPT = exports.TINY_BRAINSTORM_PROMPT = exports.TINY_FOLLOW_UP_QUESTIONS_PROMPT = exports.TINY_FOLLOWUP_PROMPT = exports.TINY_RECAP_PROMPT = exports.TINY_ASSIST_PROMPT = exports.TINY_WHAT_TO_ANSWER_PROMPT = exports.TINY_ANSWER_PROMPT = exports.TINY_SYSTEM_PROMPT = exports.TINY_CORE = exports.BRAINSTORM_MODE_PROMPT = exports.buildCodeHintMessage = exports.CODE_HINT_PROMPT = exports.GROQ_FOLLOWUP_EMAIL_PROMPT = exports.FOLLOWUP_EMAIL_PROMPT = exports.GROQ_SUMMARY_JSON_PROMPT = exports.GROQ_TITLE_PROMPT = exports.WHAT_TO_ANSWER_PROMPT = exports.FOLLOWUP_MODE_PROMPT = exports.ASSIST_MODE_PROMPT = exports.ANSWER_MODE_PROMPT = exports.HARD_SYSTEM_PROMPT = exports.MODE_CONFIGS = exports.routeLLMProviders = exports.planNextAssistantAction = exports.warmupIntentClassifier = exports.getAnswerShapeGuidance = exports.classifyIntent = exports.formatTemporalContextForPrompt = exports.buildTemporalContext = exports.prepareTranscriptForWhatToAnswer = exports.formatTranscriptForLLM = exports.sparsifyTranscript = exports.cleanTranscript = exports.validateResponse = exports.clampResponse = exports.WhatToAnswerLLM = exports.RecapLLM = exports.FollowUpQuestionsLLM = exports.FollowUpLLM = exports.CodeHintLLM = exports.ClarifyLLM = exports.BrainstormLLM = exports.AssistLLM = exports.AnswerLLM = void 0;
exports.parseOllamaSize = exports.truncateTranscriptToFit = exports.estimateTokens = exports.selectPromptTier = exports.getModelCapabilities = exports.TINY_PROMPTS_SET = exports.TINY_MODE_TECHNICAL_INTERVIEW_PROMPT = exports.TINY_MODE_LECTURE_PROMPT = exports.TINY_MODE_TEAM_MEET_PROMPT = exports.TINY_MODE_RECRUITING_PROMPT = exports.TINY_MODE_SALES_PROMPT = exports.TINY_MODE_LOOKING_FOR_WORK_PROMPT = void 0;
var AnswerLLM_1 = require("./AnswerLLM");
Object.defineProperty(exports, "AnswerLLM", { enumerable: true, get: function () { return AnswerLLM_1.AnswerLLM; } });
var AssistLLM_1 = require("./AssistLLM");
Object.defineProperty(exports, "AssistLLM", { enumerable: true, get: function () { return AssistLLM_1.AssistLLM; } });
var BrainstormLLM_1 = require("./BrainstormLLM");
Object.defineProperty(exports, "BrainstormLLM", { enumerable: true, get: function () { return BrainstormLLM_1.BrainstormLLM; } });
var ClarifyLLM_1 = require("./ClarifyLLM");
Object.defineProperty(exports, "ClarifyLLM", { enumerable: true, get: function () { return ClarifyLLM_1.ClarifyLLM; } });
var CodeHintLLM_1 = require("./CodeHintLLM");
Object.defineProperty(exports, "CodeHintLLM", { enumerable: true, get: function () { return CodeHintLLM_1.CodeHintLLM; } });
var FollowUpLLM_1 = require("./FollowUpLLM");
Object.defineProperty(exports, "FollowUpLLM", { enumerable: true, get: function () { return FollowUpLLM_1.FollowUpLLM; } });
var FollowUpQuestionsLLM_1 = require("./FollowUpQuestionsLLM");
Object.defineProperty(exports, "FollowUpQuestionsLLM", { enumerable: true, get: function () { return FollowUpQuestionsLLM_1.FollowUpQuestionsLLM; } });
var RecapLLM_1 = require("./RecapLLM");
Object.defineProperty(exports, "RecapLLM", { enumerable: true, get: function () { return RecapLLM_1.RecapLLM; } });
var WhatToAnswerLLM_1 = require("./WhatToAnswerLLM");
Object.defineProperty(exports, "WhatToAnswerLLM", { enumerable: true, get: function () { return WhatToAnswerLLM_1.WhatToAnswerLLM; } });
var postProcessor_1 = require("./postProcessor");
Object.defineProperty(exports, "clampResponse", { enumerable: true, get: function () { return postProcessor_1.clampResponse; } });
Object.defineProperty(exports, "validateResponse", { enumerable: true, get: function () { return postProcessor_1.validateResponse; } });
var transcriptCleaner_1 = require("./transcriptCleaner");
Object.defineProperty(exports, "cleanTranscript", { enumerable: true, get: function () { return transcriptCleaner_1.cleanTranscript; } });
Object.defineProperty(exports, "sparsifyTranscript", { enumerable: true, get: function () { return transcriptCleaner_1.sparsifyTranscript; } });
Object.defineProperty(exports, "formatTranscriptForLLM", { enumerable: true, get: function () { return transcriptCleaner_1.formatTranscriptForLLM; } });
Object.defineProperty(exports, "prepareTranscriptForWhatToAnswer", { enumerable: true, get: function () { return transcriptCleaner_1.prepareTranscriptForWhatToAnswer; } });
var TemporalContextBuilder_1 = require("./TemporalContextBuilder");
Object.defineProperty(exports, "buildTemporalContext", { enumerable: true, get: function () { return TemporalContextBuilder_1.buildTemporalContext; } });
Object.defineProperty(exports, "formatTemporalContextForPrompt", { enumerable: true, get: function () { return TemporalContextBuilder_1.formatTemporalContextForPrompt; } });
var IntentClassifier_1 = require("./IntentClassifier");
Object.defineProperty(exports, "classifyIntent", { enumerable: true, get: function () { return IntentClassifier_1.classifyIntent; } });
Object.defineProperty(exports, "getAnswerShapeGuidance", { enumerable: true, get: function () { return IntentClassifier_1.getAnswerShapeGuidance; } });
Object.defineProperty(exports, "warmupIntentClassifier", { enumerable: true, get: function () { return IntentClassifier_1.warmupIntentClassifier; } });
var PlannerDecision_1 = require("./PlannerDecision");
Object.defineProperty(exports, "planNextAssistantAction", { enumerable: true, get: function () { return PlannerDecision_1.planNextAssistantAction; } });
var ProviderRouter_1 = require("./ProviderRouter");
Object.defineProperty(exports, "routeLLMProviders", { enumerable: true, get: function () { return ProviderRouter_1.routeLLMProviders; } });
var types_1 = require("./types");
Object.defineProperty(exports, "MODE_CONFIGS", { enumerable: true, get: function () { return types_1.MODE_CONFIGS; } });
var prompts_1 = require("./prompts");
Object.defineProperty(exports, "HARD_SYSTEM_PROMPT", { enumerable: true, get: function () { return prompts_1.HARD_SYSTEM_PROMPT; } });
Object.defineProperty(exports, "ANSWER_MODE_PROMPT", { enumerable: true, get: function () { return prompts_1.ANSWER_MODE_PROMPT; } });
Object.defineProperty(exports, "ASSIST_MODE_PROMPT", { enumerable: true, get: function () { return prompts_1.ASSIST_MODE_PROMPT; } });
Object.defineProperty(exports, "FOLLOWUP_MODE_PROMPT", { enumerable: true, get: function () { return prompts_1.FOLLOWUP_MODE_PROMPT; } });
Object.defineProperty(exports, "WHAT_TO_ANSWER_PROMPT", { enumerable: true, get: function () { return prompts_1.WHAT_TO_ANSWER_PROMPT; } });
Object.defineProperty(exports, "GROQ_TITLE_PROMPT", { enumerable: true, get: function () { return prompts_1.GROQ_TITLE_PROMPT; } });
Object.defineProperty(exports, "GROQ_SUMMARY_JSON_PROMPT", { enumerable: true, get: function () { return prompts_1.GROQ_SUMMARY_JSON_PROMPT; } });
Object.defineProperty(exports, "FOLLOWUP_EMAIL_PROMPT", { enumerable: true, get: function () { return prompts_1.FOLLOWUP_EMAIL_PROMPT; } });
Object.defineProperty(exports, "GROQ_FOLLOWUP_EMAIL_PROMPT", { enumerable: true, get: function () { return prompts_1.GROQ_FOLLOWUP_EMAIL_PROMPT; } });
Object.defineProperty(exports, "CODE_HINT_PROMPT", { enumerable: true, get: function () { return prompts_1.CODE_HINT_PROMPT; } });
Object.defineProperty(exports, "buildCodeHintMessage", { enumerable: true, get: function () { return prompts_1.buildCodeHintMessage; } });
Object.defineProperty(exports, "BRAINSTORM_MODE_PROMPT", { enumerable: true, get: function () { return prompts_1.BRAINSTORM_MODE_PROMPT; } });
var tinyPrompts_1 = require("./tinyPrompts");
Object.defineProperty(exports, "TINY_CORE", { enumerable: true, get: function () { return tinyPrompts_1.TINY_CORE; } });
Object.defineProperty(exports, "TINY_SYSTEM_PROMPT", { enumerable: true, get: function () { return tinyPrompts_1.TINY_SYSTEM_PROMPT; } });
Object.defineProperty(exports, "TINY_ANSWER_PROMPT", { enumerable: true, get: function () { return tinyPrompts_1.TINY_ANSWER_PROMPT; } });
Object.defineProperty(exports, "TINY_WHAT_TO_ANSWER_PROMPT", { enumerable: true, get: function () { return tinyPrompts_1.TINY_WHAT_TO_ANSWER_PROMPT; } });
Object.defineProperty(exports, "TINY_ASSIST_PROMPT", { enumerable: true, get: function () { return tinyPrompts_1.TINY_ASSIST_PROMPT; } });
Object.defineProperty(exports, "TINY_RECAP_PROMPT", { enumerable: true, get: function () { return tinyPrompts_1.TINY_RECAP_PROMPT; } });
Object.defineProperty(exports, "TINY_FOLLOWUP_PROMPT", { enumerable: true, get: function () { return tinyPrompts_1.TINY_FOLLOWUP_PROMPT; } });
Object.defineProperty(exports, "TINY_FOLLOW_UP_QUESTIONS_PROMPT", { enumerable: true, get: function () { return tinyPrompts_1.TINY_FOLLOW_UP_QUESTIONS_PROMPT; } });
Object.defineProperty(exports, "TINY_BRAINSTORM_PROMPT", { enumerable: true, get: function () { return tinyPrompts_1.TINY_BRAINSTORM_PROMPT; } });
Object.defineProperty(exports, "TINY_CLARIFY_PROMPT", { enumerable: true, get: function () { return tinyPrompts_1.TINY_CLARIFY_PROMPT; } });
Object.defineProperty(exports, "TINY_CODE_HINT_PROMPT", { enumerable: true, get: function () { return tinyPrompts_1.TINY_CODE_HINT_PROMPT; } });
Object.defineProperty(exports, "TINY_TITLE_PROMPT", { enumerable: true, get: function () { return tinyPrompts_1.TINY_TITLE_PROMPT; } });
Object.defineProperty(exports, "TINY_SUMMARY_JSON_PROMPT", { enumerable: true, get: function () { return tinyPrompts_1.TINY_SUMMARY_JSON_PROMPT; } });
Object.defineProperty(exports, "TINY_FOLLOWUP_EMAIL_PROMPT", { enumerable: true, get: function () { return tinyPrompts_1.TINY_FOLLOWUP_EMAIL_PROMPT; } });
Object.defineProperty(exports, "TINY_MODE_GENERAL_PROMPT", { enumerable: true, get: function () { return tinyPrompts_1.TINY_MODE_GENERAL_PROMPT; } });
Object.defineProperty(exports, "TINY_MODE_LOOKING_FOR_WORK_PROMPT", { enumerable: true, get: function () { return tinyPrompts_1.TINY_MODE_LOOKING_FOR_WORK_PROMPT; } });
Object.defineProperty(exports, "TINY_MODE_SALES_PROMPT", { enumerable: true, get: function () { return tinyPrompts_1.TINY_MODE_SALES_PROMPT; } });
Object.defineProperty(exports, "TINY_MODE_RECRUITING_PROMPT", { enumerable: true, get: function () { return tinyPrompts_1.TINY_MODE_RECRUITING_PROMPT; } });
Object.defineProperty(exports, "TINY_MODE_TEAM_MEET_PROMPT", { enumerable: true, get: function () { return tinyPrompts_1.TINY_MODE_TEAM_MEET_PROMPT; } });
Object.defineProperty(exports, "TINY_MODE_LECTURE_PROMPT", { enumerable: true, get: function () { return tinyPrompts_1.TINY_MODE_LECTURE_PROMPT; } });
Object.defineProperty(exports, "TINY_MODE_TECHNICAL_INTERVIEW_PROMPT", { enumerable: true, get: function () { return tinyPrompts_1.TINY_MODE_TECHNICAL_INTERVIEW_PROMPT; } });
Object.defineProperty(exports, "TINY_PROMPTS_SET", { enumerable: true, get: function () { return tinyPrompts_1.TINY_PROMPTS_SET; } });
var modelCapabilities_1 = require("./modelCapabilities");
Object.defineProperty(exports, "getModelCapabilities", { enumerable: true, get: function () { return modelCapabilities_1.getModelCapabilities; } });
Object.defineProperty(exports, "selectPromptTier", { enumerable: true, get: function () { return modelCapabilities_1.selectPromptTier; } });
Object.defineProperty(exports, "estimateTokens", { enumerable: true, get: function () { return modelCapabilities_1.estimateTokens; } });
Object.defineProperty(exports, "truncateTranscriptToFit", { enumerable: true, get: function () { return modelCapabilities_1.truncateTranscriptToFit; } });
Object.defineProperty(exports, "parseOllamaSize", { enumerable: true, get: function () { return modelCapabilities_1.parseOllamaSize; } });
//# sourceMappingURL=index.js.map